#' Restore Variable Labels
#'
#' @description Re-applies variable labels that have been extracted from the data frame earlier. Supports mapping for renamed variables.
#'
#' @param data A data frame to label.
#' @param label_list A named list of labels (generated by \code{pull_labels}).
#' @param renamed A named character vector mapping new names to old names (e.g. c("new_name" = "old_name")).
#' @return The data frame with restored labels.
#' @export
restore_labels <- function(data, label_list, renamed = NULL) {
  # 1. Standard: Direkte Namensübereinstimmungen wiederherstellen
  for (col in names(data)) {
    if (col %in% names(label_list)) {
      attr(data[[col]], "label") <- label_list[[col]]
    }
  }

  # 2. Advanced: Umbenannte/Neue Variablen labeln
  if (!is.null(renamed)) {
    for (new_name in names(renamed)) {
      old_name <- renamed[[new_name]]

      # Prüfen: Existiert die neue Spalte im Datensatz UND haben wir ein Label für die alte?
      if (new_name %in% names(data) && old_name %in% names(label_list)) {
        attr(data[[new_name]], "label") <- label_list[[old_name]]
      }
    }
  }

  invisible(data)
}
